# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ethan/code/projet-ldp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ethan/code/projet-ldp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ethan/code/projet-ldp/CMakeFiles /home/ethan/code/projet-ldp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ethan/code/projet-ldp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named casse-briques

# Build rule for target.
casse-briques: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 casse-briques
.PHONY : casse-briques

# fast build rule for target.
casse-briques/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/build
.PHONY : casse-briques/fast

controller/controller.o: controller/controller.cpp.o
.PHONY : controller/controller.o

# target to build an object file
controller/controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/controller/controller.cpp.o
.PHONY : controller/controller.cpp.o

controller/controller.i: controller/controller.cpp.i
.PHONY : controller/controller.i

# target to preprocess a source file
controller/controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/controller/controller.cpp.i
.PHONY : controller/controller.cpp.i

controller/controller.s: controller/controller.cpp.s
.PHONY : controller/controller.s

# target to generate assembly for a file
controller/controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/controller/controller.cpp.s
.PHONY : controller/controller.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/main.cpp.s
.PHONY : main.cpp.s

model/ball/ball.o: model/ball/ball.cpp.o
.PHONY : model/ball/ball.o

# target to build an object file
model/ball/ball.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/ball/ball.cpp.o
.PHONY : model/ball/ball.cpp.o

model/ball/ball.i: model/ball/ball.cpp.i
.PHONY : model/ball/ball.i

# target to preprocess a source file
model/ball/ball.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/ball/ball.cpp.i
.PHONY : model/ball/ball.cpp.i

model/ball/ball.s: model/ball/ball.cpp.s
.PHONY : model/ball/ball.s

# target to generate assembly for a file
model/ball/ball.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/ball/ball.cpp.s
.PHONY : model/ball/ball.cpp.s

model/border/border.o: model/border/border.cpp.o
.PHONY : model/border/border.o

# target to build an object file
model/border/border.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/border/border.cpp.o
.PHONY : model/border/border.cpp.o

model/border/border.i: model/border/border.cpp.i
.PHONY : model/border/border.i

# target to preprocess a source file
model/border/border.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/border/border.cpp.i
.PHONY : model/border/border.cpp.i

model/border/border.s: model/border/border.cpp.s
.PHONY : model/border/border.s

# target to generate assembly for a file
model/border/border.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/border/border.cpp.s
.PHONY : model/border/border.cpp.s

model/bounceable/bounceable.o: model/bounceable/bounceable.cpp.o
.PHONY : model/bounceable/bounceable.o

# target to build an object file
model/bounceable/bounceable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/bounceable/bounceable.cpp.o
.PHONY : model/bounceable/bounceable.cpp.o

model/bounceable/bounceable.i: model/bounceable/bounceable.cpp.i
.PHONY : model/bounceable/bounceable.i

# target to preprocess a source file
model/bounceable/bounceable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/bounceable/bounceable.cpp.i
.PHONY : model/bounceable/bounceable.cpp.i

model/bounceable/bounceable.s: model/bounceable/bounceable.cpp.s
.PHONY : model/bounceable/bounceable.s

# target to generate assembly for a file
model/bounceable/bounceable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/bounceable/bounceable.cpp.s
.PHONY : model/bounceable/bounceable.cpp.s

model/bounding_box/bounding_box.o: model/bounding_box/bounding_box.cpp.o
.PHONY : model/bounding_box/bounding_box.o

# target to build an object file
model/bounding_box/bounding_box.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/bounding_box/bounding_box.cpp.o
.PHONY : model/bounding_box/bounding_box.cpp.o

model/bounding_box/bounding_box.i: model/bounding_box/bounding_box.cpp.i
.PHONY : model/bounding_box/bounding_box.i

# target to preprocess a source file
model/bounding_box/bounding_box.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/bounding_box/bounding_box.cpp.i
.PHONY : model/bounding_box/bounding_box.cpp.i

model/bounding_box/bounding_box.s: model/bounding_box/bounding_box.cpp.s
.PHONY : model/bounding_box/bounding_box.s

# target to generate assembly for a file
model/bounding_box/bounding_box.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/bounding_box/bounding_box.cpp.s
.PHONY : model/bounding_box/bounding_box.cpp.s

model/brick/basic_brick.o: model/brick/basic_brick.cpp.o
.PHONY : model/brick/basic_brick.o

# target to build an object file
model/brick/basic_brick.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/brick/basic_brick.cpp.o
.PHONY : model/brick/basic_brick.cpp.o

model/brick/basic_brick.i: model/brick/basic_brick.cpp.i
.PHONY : model/brick/basic_brick.i

# target to preprocess a source file
model/brick/basic_brick.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/brick/basic_brick.cpp.i
.PHONY : model/brick/basic_brick.cpp.i

model/brick/basic_brick.s: model/brick/basic_brick.cpp.s
.PHONY : model/brick/basic_brick.s

# target to generate assembly for a file
model/brick/basic_brick.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/brick/basic_brick.cpp.s
.PHONY : model/brick/basic_brick.cpp.s

model/brick/brick.o: model/brick/brick.cpp.o
.PHONY : model/brick/brick.o

# target to build an object file
model/brick/brick.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/brick/brick.cpp.o
.PHONY : model/brick/brick.cpp.o

model/brick/brick.i: model/brick/brick.cpp.i
.PHONY : model/brick/brick.i

# target to preprocess a source file
model/brick/brick.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/brick/brick.cpp.i
.PHONY : model/brick/brick.cpp.i

model/brick/brick.s: model/brick/brick.cpp.s
.PHONY : model/brick/brick.s

# target to generate assembly for a file
model/brick/brick.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/brick/brick.cpp.s
.PHONY : model/brick/brick.cpp.s

model/brick/gold_brick.o: model/brick/gold_brick.cpp.o
.PHONY : model/brick/gold_brick.o

# target to build an object file
model/brick/gold_brick.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/brick/gold_brick.cpp.o
.PHONY : model/brick/gold_brick.cpp.o

model/brick/gold_brick.i: model/brick/gold_brick.cpp.i
.PHONY : model/brick/gold_brick.i

# target to preprocess a source file
model/brick/gold_brick.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/brick/gold_brick.cpp.i
.PHONY : model/brick/gold_brick.cpp.i

model/brick/gold_brick.s: model/brick/gold_brick.cpp.s
.PHONY : model/brick/gold_brick.s

# target to generate assembly for a file
model/brick/gold_brick.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/brick/gold_brick.cpp.s
.PHONY : model/brick/gold_brick.cpp.s

model/game_board/game_board.o: model/game_board/game_board.cpp.o
.PHONY : model/game_board/game_board.o

# target to build an object file
model/game_board/game_board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/game_board/game_board.cpp.o
.PHONY : model/game_board/game_board.cpp.o

model/game_board/game_board.i: model/game_board/game_board.cpp.i
.PHONY : model/game_board/game_board.i

# target to preprocess a source file
model/game_board/game_board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/game_board/game_board.cpp.i
.PHONY : model/game_board/game_board.cpp.i

model/game_board/game_board.s: model/game_board/game_board.cpp.s
.PHONY : model/game_board/game_board.s

# target to generate assembly for a file
model/game_board/game_board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/game_board/game_board.cpp.s
.PHONY : model/game_board/game_board.cpp.s

model/life/life.o: model/life/life.cpp.o
.PHONY : model/life/life.o

# target to build an object file
model/life/life.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/life/life.cpp.o
.PHONY : model/life/life.cpp.o

model/life/life.i: model/life/life.cpp.i
.PHONY : model/life/life.i

# target to preprocess a source file
model/life/life.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/life/life.cpp.i
.PHONY : model/life/life.cpp.i

model/life/life.s: model/life/life.cpp.s
.PHONY : model/life/life.s

# target to generate assembly for a file
model/life/life.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/life/life.cpp.s
.PHONY : model/life/life.cpp.s

model/model.o: model/model.cpp.o
.PHONY : model/model.o

# target to build an object file
model/model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/model.cpp.o
.PHONY : model/model.cpp.o

model/model.i: model/model.cpp.i
.PHONY : model/model.i

# target to preprocess a source file
model/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/model.cpp.i
.PHONY : model/model.cpp.i

model/model.s: model/model.cpp.s
.PHONY : model/model.s

# target to generate assembly for a file
model/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/model.cpp.s
.PHONY : model/model.cpp.s

model/racket/racket.o: model/racket/racket.cpp.o
.PHONY : model/racket/racket.o

# target to build an object file
model/racket/racket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/racket/racket.cpp.o
.PHONY : model/racket/racket.cpp.o

model/racket/racket.i: model/racket/racket.cpp.i
.PHONY : model/racket/racket.i

# target to preprocess a source file
model/racket/racket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/racket/racket.cpp.i
.PHONY : model/racket/racket.cpp.i

model/racket/racket.s: model/racket/racket.cpp.s
.PHONY : model/racket/racket.s

# target to generate assembly for a file
model/racket/racket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/racket/racket.cpp.s
.PHONY : model/racket/racket.cpp.s

model/score/score.o: model/score/score.cpp.o
.PHONY : model/score/score.o

# target to build an object file
model/score/score.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/score/score.cpp.o
.PHONY : model/score/score.cpp.o

model/score/score.i: model/score/score.cpp.i
.PHONY : model/score/score.i

# target to preprocess a source file
model/score/score.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/score/score.cpp.i
.PHONY : model/score/score.cpp.i

model/score/score.s: model/score/score.cpp.s
.PHONY : model/score/score.s

# target to generate assembly for a file
model/score/score.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/score/score.cpp.s
.PHONY : model/score/score.cpp.s

model/vec2/vec2.o: model/vec2/vec2.cpp.o
.PHONY : model/vec2/vec2.o

# target to build an object file
model/vec2/vec2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/vec2/vec2.cpp.o
.PHONY : model/vec2/vec2.cpp.o

model/vec2/vec2.i: model/vec2/vec2.cpp.i
.PHONY : model/vec2/vec2.i

# target to preprocess a source file
model/vec2/vec2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/vec2/vec2.cpp.i
.PHONY : model/vec2/vec2.cpp.i

model/vec2/vec2.s: model/vec2/vec2.cpp.s
.PHONY : model/vec2/vec2.s

# target to generate assembly for a file
model/vec2/vec2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/casse-briques.dir/build.make CMakeFiles/casse-briques.dir/model/vec2/vec2.cpp.s
.PHONY : model/vec2/vec2.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... casse-briques"
	@echo "... controller/controller.o"
	@echo "... controller/controller.i"
	@echo "... controller/controller.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... model/ball/ball.o"
	@echo "... model/ball/ball.i"
	@echo "... model/ball/ball.s"
	@echo "... model/border/border.o"
	@echo "... model/border/border.i"
	@echo "... model/border/border.s"
	@echo "... model/bounceable/bounceable.o"
	@echo "... model/bounceable/bounceable.i"
	@echo "... model/bounceable/bounceable.s"
	@echo "... model/bounding_box/bounding_box.o"
	@echo "... model/bounding_box/bounding_box.i"
	@echo "... model/bounding_box/bounding_box.s"
	@echo "... model/brick/basic_brick.o"
	@echo "... model/brick/basic_brick.i"
	@echo "... model/brick/basic_brick.s"
	@echo "... model/brick/brick.o"
	@echo "... model/brick/brick.i"
	@echo "... model/brick/brick.s"
	@echo "... model/brick/gold_brick.o"
	@echo "... model/brick/gold_brick.i"
	@echo "... model/brick/gold_brick.s"
	@echo "... model/game_board/game_board.o"
	@echo "... model/game_board/game_board.i"
	@echo "... model/game_board/game_board.s"
	@echo "... model/life/life.o"
	@echo "... model/life/life.i"
	@echo "... model/life/life.s"
	@echo "... model/model.o"
	@echo "... model/model.i"
	@echo "... model/model.s"
	@echo "... model/racket/racket.o"
	@echo "... model/racket/racket.i"
	@echo "... model/racket/racket.s"
	@echo "... model/score/score.o"
	@echo "... model/score/score.i"
	@echo "... model/score/score.s"
	@echo "... model/vec2/vec2.o"
	@echo "... model/vec2/vec2.i"
	@echo "... model/vec2/vec2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

