# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "C:\Users\ethan\OneDrive\Documents\Programmation Perso\arkanoid"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "C:\Users\ethan\OneDrive\Documents\Programmation Perso\arkanoid"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\ethan\OneDrive\Documents\Programmation Perso\arkanoid\CMakeFiles" "C:\Users\ethan\OneDrive\Documents\Programmation Perso\arkanoid\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "C:\Users\ethan\OneDrive\Documents\Programmation Perso\arkanoid\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named arkanoid

# Build rule for target.
arkanoid: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 arkanoid
.PHONY : arkanoid

# fast build rule for target.
arkanoid/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/build
.PHONY : arkanoid/fast

src/controller/controller_game.obj: src/controller/controller_game.cpp.obj
.PHONY : src/controller/controller_game.obj

# target to build an object file
src/controller/controller_game.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/controller/controller_game.cpp.obj
.PHONY : src/controller/controller_game.cpp.obj

src/controller/controller_game.i: src/controller/controller_game.cpp.i
.PHONY : src/controller/controller_game.i

# target to preprocess a source file
src/controller/controller_game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/controller/controller_game.cpp.i
.PHONY : src/controller/controller_game.cpp.i

src/controller/controller_game.s: src/controller/controller_game.cpp.s
.PHONY : src/controller/controller_game.s

# target to generate assembly for a file
src/controller/controller_game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/controller/controller_game.cpp.s
.PHONY : src/controller/controller_game.cpp.s

src/controller/level_manager/level_manager.obj: src/controller/level_manager/level_manager.cpp.obj
.PHONY : src/controller/level_manager/level_manager.obj

# target to build an object file
src/controller/level_manager/level_manager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/controller/level_manager/level_manager.cpp.obj
.PHONY : src/controller/level_manager/level_manager.cpp.obj

src/controller/level_manager/level_manager.i: src/controller/level_manager/level_manager.cpp.i
.PHONY : src/controller/level_manager/level_manager.i

# target to preprocess a source file
src/controller/level_manager/level_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/controller/level_manager/level_manager.cpp.i
.PHONY : src/controller/level_manager/level_manager.cpp.i

src/controller/level_manager/level_manager.s: src/controller/level_manager/level_manager.cpp.s
.PHONY : src/controller/level_manager/level_manager.s

# target to generate assembly for a file
src/controller/level_manager/level_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/controller/level_manager/level_manager.cpp.s
.PHONY : src/controller/level_manager/level_manager.cpp.s

src/log/log.obj: src/log/log.cpp.obj
.PHONY : src/log/log.obj

# target to build an object file
src/log/log.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/log/log.cpp.obj
.PHONY : src/log/log.cpp.obj

src/log/log.i: src/log/log.cpp.i
.PHONY : src/log/log.i

# target to preprocess a source file
src/log/log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/log/log.cpp.i
.PHONY : src/log/log.cpp.i

src/log/log.s: src/log/log.cpp.s
.PHONY : src/log/log.s

# target to generate assembly for a file
src/log/log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/log/log.cpp.s
.PHONY : src/log/log.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/model/ball/ball.obj: src/model/ball/ball.cpp.obj
.PHONY : src/model/ball/ball.obj

# target to build an object file
src/model/ball/ball.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/ball/ball.cpp.obj
.PHONY : src/model/ball/ball.cpp.obj

src/model/ball/ball.i: src/model/ball/ball.cpp.i
.PHONY : src/model/ball/ball.i

# target to preprocess a source file
src/model/ball/ball.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/ball/ball.cpp.i
.PHONY : src/model/ball/ball.cpp.i

src/model/ball/ball.s: src/model/ball/ball.cpp.s
.PHONY : src/model/ball/ball.s

# target to generate assembly for a file
src/model/ball/ball.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/ball/ball.cpp.s
.PHONY : src/model/ball/ball.cpp.s

src/model/bonus/abstract_timed_bonus.obj: src/model/bonus/abstract_timed_bonus.cpp.obj
.PHONY : src/model/bonus/abstract_timed_bonus.obj

# target to build an object file
src/model/bonus/abstract_timed_bonus.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/bonus/abstract_timed_bonus.cpp.obj
.PHONY : src/model/bonus/abstract_timed_bonus.cpp.obj

src/model/bonus/abstract_timed_bonus.i: src/model/bonus/abstract_timed_bonus.cpp.i
.PHONY : src/model/bonus/abstract_timed_bonus.i

# target to preprocess a source file
src/model/bonus/abstract_timed_bonus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/bonus/abstract_timed_bonus.cpp.i
.PHONY : src/model/bonus/abstract_timed_bonus.cpp.i

src/model/bonus/abstract_timed_bonus.s: src/model/bonus/abstract_timed_bonus.cpp.s
.PHONY : src/model/bonus/abstract_timed_bonus.s

# target to generate assembly for a file
src/model/bonus/abstract_timed_bonus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/bonus/abstract_timed_bonus.cpp.s
.PHONY : src/model/bonus/abstract_timed_bonus.cpp.s

src/model/bonus/basic_timed_bonus.obj: src/model/bonus/basic_timed_bonus.cpp.obj
.PHONY : src/model/bonus/basic_timed_bonus.obj

# target to build an object file
src/model/bonus/basic_timed_bonus.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/bonus/basic_timed_bonus.cpp.obj
.PHONY : src/model/bonus/basic_timed_bonus.cpp.obj

src/model/bonus/basic_timed_bonus.i: src/model/bonus/basic_timed_bonus.cpp.i
.PHONY : src/model/bonus/basic_timed_bonus.i

# target to preprocess a source file
src/model/bonus/basic_timed_bonus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/bonus/basic_timed_bonus.cpp.i
.PHONY : src/model/bonus/basic_timed_bonus.cpp.i

src/model/bonus/basic_timed_bonus.s: src/model/bonus/basic_timed_bonus.cpp.s
.PHONY : src/model/bonus/basic_timed_bonus.s

# target to generate assembly for a file
src/model/bonus/basic_timed_bonus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/bonus/basic_timed_bonus.cpp.s
.PHONY : src/model/bonus/basic_timed_bonus.cpp.s

src/model/bonus/slowdown_bonus.obj: src/model/bonus/slowdown_bonus.cpp.obj
.PHONY : src/model/bonus/slowdown_bonus.obj

# target to build an object file
src/model/bonus/slowdown_bonus.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/bonus/slowdown_bonus.cpp.obj
.PHONY : src/model/bonus/slowdown_bonus.cpp.obj

src/model/bonus/slowdown_bonus.i: src/model/bonus/slowdown_bonus.cpp.i
.PHONY : src/model/bonus/slowdown_bonus.i

# target to preprocess a source file
src/model/bonus/slowdown_bonus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/bonus/slowdown_bonus.cpp.i
.PHONY : src/model/bonus/slowdown_bonus.cpp.i

src/model/bonus/slowdown_bonus.s: src/model/bonus/slowdown_bonus.cpp.s
.PHONY : src/model/bonus/slowdown_bonus.s

# target to generate assembly for a file
src/model/bonus/slowdown_bonus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/bonus/slowdown_bonus.cpp.s
.PHONY : src/model/bonus/slowdown_bonus.cpp.s

src/model/bonus_pill/bonus_pill.obj: src/model/bonus_pill/bonus_pill.cpp.obj
.PHONY : src/model/bonus_pill/bonus_pill.obj

# target to build an object file
src/model/bonus_pill/bonus_pill.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/bonus_pill/bonus_pill.cpp.obj
.PHONY : src/model/bonus_pill/bonus_pill.cpp.obj

src/model/bonus_pill/bonus_pill.i: src/model/bonus_pill/bonus_pill.cpp.i
.PHONY : src/model/bonus_pill/bonus_pill.i

# target to preprocess a source file
src/model/bonus_pill/bonus_pill.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/bonus_pill/bonus_pill.cpp.i
.PHONY : src/model/bonus_pill/bonus_pill.cpp.i

src/model/bonus_pill/bonus_pill.s: src/model/bonus_pill/bonus_pill.cpp.s
.PHONY : src/model/bonus_pill/bonus_pill.s

# target to generate assembly for a file
src/model/bonus_pill/bonus_pill.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/bonus_pill/bonus_pill.cpp.s
.PHONY : src/model/bonus_pill/bonus_pill.cpp.s

src/model/border/border.obj: src/model/border/border.cpp.obj
.PHONY : src/model/border/border.obj

# target to build an object file
src/model/border/border.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/border/border.cpp.obj
.PHONY : src/model/border/border.cpp.obj

src/model/border/border.i: src/model/border/border.cpp.i
.PHONY : src/model/border/border.i

# target to preprocess a source file
src/model/border/border.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/border/border.cpp.i
.PHONY : src/model/border/border.cpp.i

src/model/border/border.s: src/model/border/border.cpp.s
.PHONY : src/model/border/border.s

# target to generate assembly for a file
src/model/border/border.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/border/border.cpp.s
.PHONY : src/model/border/border.cpp.s

src/model/bounceable/bounceable.obj: src/model/bounceable/bounceable.cpp.obj
.PHONY : src/model/bounceable/bounceable.obj

# target to build an object file
src/model/bounceable/bounceable.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/bounceable/bounceable.cpp.obj
.PHONY : src/model/bounceable/bounceable.cpp.obj

src/model/bounceable/bounceable.i: src/model/bounceable/bounceable.cpp.i
.PHONY : src/model/bounceable/bounceable.i

# target to preprocess a source file
src/model/bounceable/bounceable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/bounceable/bounceable.cpp.i
.PHONY : src/model/bounceable/bounceable.cpp.i

src/model/bounceable/bounceable.s: src/model/bounceable/bounceable.cpp.s
.PHONY : src/model/bounceable/bounceable.s

# target to generate assembly for a file
src/model/bounceable/bounceable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/bounceable/bounceable.cpp.s
.PHONY : src/model/bounceable/bounceable.cpp.s

src/model/brick/abstract_brick.obj: src/model/brick/abstract_brick.cpp.obj
.PHONY : src/model/brick/abstract_brick.obj

# target to build an object file
src/model/brick/abstract_brick.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/brick/abstract_brick.cpp.obj
.PHONY : src/model/brick/abstract_brick.cpp.obj

src/model/brick/abstract_brick.i: src/model/brick/abstract_brick.cpp.i
.PHONY : src/model/brick/abstract_brick.i

# target to preprocess a source file
src/model/brick/abstract_brick.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/brick/abstract_brick.cpp.i
.PHONY : src/model/brick/abstract_brick.cpp.i

src/model/brick/abstract_brick.s: src/model/brick/abstract_brick.cpp.s
.PHONY : src/model/brick/abstract_brick.s

# target to generate assembly for a file
src/model/brick/abstract_brick.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/brick/abstract_brick.cpp.s
.PHONY : src/model/brick/abstract_brick.cpp.s

src/model/brick/basic_brick.obj: src/model/brick/basic_brick.cpp.obj
.PHONY : src/model/brick/basic_brick.obj

# target to build an object file
src/model/brick/basic_brick.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/brick/basic_brick.cpp.obj
.PHONY : src/model/brick/basic_brick.cpp.obj

src/model/brick/basic_brick.i: src/model/brick/basic_brick.cpp.i
.PHONY : src/model/brick/basic_brick.i

# target to preprocess a source file
src/model/brick/basic_brick.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/brick/basic_brick.cpp.i
.PHONY : src/model/brick/basic_brick.cpp.i

src/model/brick/basic_brick.s: src/model/brick/basic_brick.cpp.s
.PHONY : src/model/brick/basic_brick.s

# target to generate assembly for a file
src/model/brick/basic_brick.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/brick/basic_brick.cpp.s
.PHONY : src/model/brick/basic_brick.cpp.s

src/model/brick/gold_brick.obj: src/model/brick/gold_brick.cpp.obj
.PHONY : src/model/brick/gold_brick.obj

# target to build an object file
src/model/brick/gold_brick.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/brick/gold_brick.cpp.obj
.PHONY : src/model/brick/gold_brick.cpp.obj

src/model/brick/gold_brick.i: src/model/brick/gold_brick.cpp.i
.PHONY : src/model/brick/gold_brick.i

# target to preprocess a source file
src/model/brick/gold_brick.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/brick/gold_brick.cpp.i
.PHONY : src/model/brick/gold_brick.cpp.i

src/model/brick/gold_brick.s: src/model/brick/gold_brick.cpp.s
.PHONY : src/model/brick/gold_brick.s

# target to generate assembly for a file
src/model/brick/gold_brick.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/brick/gold_brick.cpp.s
.PHONY : src/model/brick/gold_brick.cpp.s

src/model/game_board/game_board.obj: src/model/game_board/game_board.cpp.obj
.PHONY : src/model/game_board/game_board.obj

# target to build an object file
src/model/game_board/game_board.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/game_board/game_board.cpp.obj
.PHONY : src/model/game_board/game_board.cpp.obj

src/model/game_board/game_board.i: src/model/game_board/game_board.cpp.i
.PHONY : src/model/game_board/game_board.i

# target to preprocess a source file
src/model/game_board/game_board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/game_board/game_board.cpp.i
.PHONY : src/model/game_board/game_board.cpp.i

src/model/game_board/game_board.s: src/model/game_board/game_board.cpp.s
.PHONY : src/model/game_board/game_board.s

# target to generate assembly for a file
src/model/game_board/game_board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/game_board/game_board.cpp.s
.PHONY : src/model/game_board/game_board.cpp.s

src/model/lazer/lazer.obj: src/model/lazer/lazer.cpp.obj
.PHONY : src/model/lazer/lazer.obj

# target to build an object file
src/model/lazer/lazer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/lazer/lazer.cpp.obj
.PHONY : src/model/lazer/lazer.cpp.obj

src/model/lazer/lazer.i: src/model/lazer/lazer.cpp.i
.PHONY : src/model/lazer/lazer.i

# target to preprocess a source file
src/model/lazer/lazer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/lazer/lazer.cpp.i
.PHONY : src/model/lazer/lazer.cpp.i

src/model/lazer/lazer.s: src/model/lazer/lazer.cpp.s
.PHONY : src/model/lazer/lazer.s

# target to generate assembly for a file
src/model/lazer/lazer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/lazer/lazer.cpp.s
.PHONY : src/model/lazer/lazer.cpp.s

src/model/life_counter/life_counter.obj: src/model/life_counter/life_counter.cpp.obj
.PHONY : src/model/life_counter/life_counter.obj

# target to build an object file
src/model/life_counter/life_counter.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/life_counter/life_counter.cpp.obj
.PHONY : src/model/life_counter/life_counter.cpp.obj

src/model/life_counter/life_counter.i: src/model/life_counter/life_counter.cpp.i
.PHONY : src/model/life_counter/life_counter.i

# target to preprocess a source file
src/model/life_counter/life_counter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/life_counter/life_counter.cpp.i
.PHONY : src/model/life_counter/life_counter.cpp.i

src/model/life_counter/life_counter.s: src/model/life_counter/life_counter.cpp.s
.PHONY : src/model/life_counter/life_counter.s

# target to generate assembly for a file
src/model/life_counter/life_counter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/life_counter/life_counter.cpp.s
.PHONY : src/model/life_counter/life_counter.cpp.s

src/model/racket/racket.obj: src/model/racket/racket.cpp.obj
.PHONY : src/model/racket/racket.obj

# target to build an object file
src/model/racket/racket.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/racket/racket.cpp.obj
.PHONY : src/model/racket/racket.cpp.obj

src/model/racket/racket.i: src/model/racket/racket.cpp.i
.PHONY : src/model/racket/racket.i

# target to preprocess a source file
src/model/racket/racket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/racket/racket.cpp.i
.PHONY : src/model/racket/racket.cpp.i

src/model/racket/racket.s: src/model/racket/racket.cpp.s
.PHONY : src/model/racket/racket.s

# target to generate assembly for a file
src/model/racket/racket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/racket/racket.cpp.s
.PHONY : src/model/racket/racket.cpp.s

src/model/rectangle_shape/rectangle_shape.obj: src/model/rectangle_shape/rectangle_shape.cpp.obj
.PHONY : src/model/rectangle_shape/rectangle_shape.obj

# target to build an object file
src/model/rectangle_shape/rectangle_shape.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/rectangle_shape/rectangle_shape.cpp.obj
.PHONY : src/model/rectangle_shape/rectangle_shape.cpp.obj

src/model/rectangle_shape/rectangle_shape.i: src/model/rectangle_shape/rectangle_shape.cpp.i
.PHONY : src/model/rectangle_shape/rectangle_shape.i

# target to preprocess a source file
src/model/rectangle_shape/rectangle_shape.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/rectangle_shape/rectangle_shape.cpp.i
.PHONY : src/model/rectangle_shape/rectangle_shape.cpp.i

src/model/rectangle_shape/rectangle_shape.s: src/model/rectangle_shape/rectangle_shape.cpp.s
.PHONY : src/model/rectangle_shape/rectangle_shape.s

# target to generate assembly for a file
src/model/rectangle_shape/rectangle_shape.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/rectangle_shape/rectangle_shape.cpp.s
.PHONY : src/model/rectangle_shape/rectangle_shape.cpp.s

src/model/score_manager/score_manager.obj: src/model/score_manager/score_manager.cpp.obj
.PHONY : src/model/score_manager/score_manager.obj

# target to build an object file
src/model/score_manager/score_manager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/score_manager/score_manager.cpp.obj
.PHONY : src/model/score_manager/score_manager.cpp.obj

src/model/score_manager/score_manager.i: src/model/score_manager/score_manager.cpp.i
.PHONY : src/model/score_manager/score_manager.i

# target to preprocess a source file
src/model/score_manager/score_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/score_manager/score_manager.cpp.i
.PHONY : src/model/score_manager/score_manager.cpp.i

src/model/score_manager/score_manager.s: src/model/score_manager/score_manager.cpp.s
.PHONY : src/model/score_manager/score_manager.s

# target to generate assembly for a file
src/model/score_manager/score_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/score_manager/score_manager.cpp.s
.PHONY : src/model/score_manager/score_manager.cpp.s

src/model/vec2/vec2.obj: src/model/vec2/vec2.cpp.obj
.PHONY : src/model/vec2/vec2.obj

# target to build an object file
src/model/vec2/vec2.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/vec2/vec2.cpp.obj
.PHONY : src/model/vec2/vec2.cpp.obj

src/model/vec2/vec2.i: src/model/vec2/vec2.cpp.i
.PHONY : src/model/vec2/vec2.i

# target to preprocess a source file
src/model/vec2/vec2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/vec2/vec2.cpp.i
.PHONY : src/model/vec2/vec2.cpp.i

src/model/vec2/vec2.s: src/model/vec2/vec2.cpp.s
.PHONY : src/model/vec2/vec2.s

# target to generate assembly for a file
src/model/vec2/vec2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/model/vec2/vec2.cpp.s
.PHONY : src/model/vec2/vec2.cpp.s

src/view/canvas/canvas.obj: src/view/canvas/canvas.cpp.obj
.PHONY : src/view/canvas/canvas.obj

# target to build an object file
src/view/canvas/canvas.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/canvas/canvas.cpp.obj
.PHONY : src/view/canvas/canvas.cpp.obj

src/view/canvas/canvas.i: src/view/canvas/canvas.cpp.i
.PHONY : src/view/canvas/canvas.i

# target to preprocess a source file
src/view/canvas/canvas.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/canvas/canvas.cpp.i
.PHONY : src/view/canvas/canvas.cpp.i

src/view/canvas/canvas.s: src/view/canvas/canvas.cpp.s
.PHONY : src/view/canvas/canvas.s

# target to generate assembly for a file
src/view/canvas/canvas.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/canvas/canvas.cpp.s
.PHONY : src/view/canvas/canvas.cpp.s

src/view/color/colors.obj: src/view/color/colors.cpp.obj
.PHONY : src/view/color/colors.obj

# target to build an object file
src/view/color/colors.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/color/colors.cpp.obj
.PHONY : src/view/color/colors.cpp.obj

src/view/color/colors.i: src/view/color/colors.cpp.i
.PHONY : src/view/color/colors.i

# target to preprocess a source file
src/view/color/colors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/color/colors.cpp.i
.PHONY : src/view/color/colors.cpp.i

src/view/color/colors.s: src/view/color/colors.cpp.s
.PHONY : src/view/color/colors.s

# target to generate assembly for a file
src/view/color/colors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/color/colors.cpp.s
.PHONY : src/view/color/colors.cpp.s

src/view/display_game/display_game.obj: src/view/display_game/display_game.cpp.obj
.PHONY : src/view/display_game/display_game.obj

# target to build an object file
src/view/display_game/display_game.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/display_game/display_game.cpp.obj
.PHONY : src/view/display_game/display_game.cpp.obj

src/view/display_game/display_game.i: src/view/display_game/display_game.cpp.i
.PHONY : src/view/display_game/display_game.i

# target to preprocess a source file
src/view/display_game/display_game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/display_game/display_game.cpp.i
.PHONY : src/view/display_game/display_game.cpp.i

src/view/display_game/display_game.s: src/view/display_game/display_game.cpp.s
.PHONY : src/view/display_game/display_game.s

# target to generate assembly for a file
src/view/display_game/display_game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/display_game/display_game.cpp.s
.PHONY : src/view/display_game/display_game.cpp.s

src/view/figures/forme.obj: src/view/figures/forme.cpp.obj
.PHONY : src/view/figures/forme.obj

# target to build an object file
src/view/figures/forme.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/figures/forme.cpp.obj
.PHONY : src/view/figures/forme.cpp.obj

src/view/figures/forme.i: src/view/figures/forme.cpp.i
.PHONY : src/view/figures/forme.i

# target to preprocess a source file
src/view/figures/forme.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/figures/forme.cpp.i
.PHONY : src/view/figures/forme.cpp.i

src/view/figures/forme.s: src/view/figures/forme.cpp.s
.PHONY : src/view/figures/forme.s

# target to generate assembly for a file
src/view/figures/forme.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/figures/forme.cpp.s
.PHONY : src/view/figures/forme.cpp.s

src/view/figures/point.obj: src/view/figures/point.cpp.obj
.PHONY : src/view/figures/point.obj

# target to build an object file
src/view/figures/point.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/figures/point.cpp.obj
.PHONY : src/view/figures/point.cpp.obj

src/view/figures/point.i: src/view/figures/point.cpp.i
.PHONY : src/view/figures/point.i

# target to preprocess a source file
src/view/figures/point.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/figures/point.cpp.i
.PHONY : src/view/figures/point.cpp.i

src/view/figures/point.s: src/view/figures/point.cpp.s
.PHONY : src/view/figures/point.s

# target to generate assembly for a file
src/view/figures/point.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/figures/point.cpp.s
.PHONY : src/view/figures/point.cpp.s

src/view/piece/ball_ui.obj: src/view/piece/ball_ui.cpp.obj
.PHONY : src/view/piece/ball_ui.obj

# target to build an object file
src/view/piece/ball_ui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/piece/ball_ui.cpp.obj
.PHONY : src/view/piece/ball_ui.cpp.obj

src/view/piece/ball_ui.i: src/view/piece/ball_ui.cpp.i
.PHONY : src/view/piece/ball_ui.i

# target to preprocess a source file
src/view/piece/ball_ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/piece/ball_ui.cpp.i
.PHONY : src/view/piece/ball_ui.cpp.i

src/view/piece/ball_ui.s: src/view/piece/ball_ui.cpp.s
.PHONY : src/view/piece/ball_ui.s

# target to generate assembly for a file
src/view/piece/ball_ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/piece/ball_ui.cpp.s
.PHONY : src/view/piece/ball_ui.cpp.s

src/view/piece/bonus_pill_ui.obj: src/view/piece/bonus_pill_ui.cpp.obj
.PHONY : src/view/piece/bonus_pill_ui.obj

# target to build an object file
src/view/piece/bonus_pill_ui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/piece/bonus_pill_ui.cpp.obj
.PHONY : src/view/piece/bonus_pill_ui.cpp.obj

src/view/piece/bonus_pill_ui.i: src/view/piece/bonus_pill_ui.cpp.i
.PHONY : src/view/piece/bonus_pill_ui.i

# target to preprocess a source file
src/view/piece/bonus_pill_ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/piece/bonus_pill_ui.cpp.i
.PHONY : src/view/piece/bonus_pill_ui.cpp.i

src/view/piece/bonus_pill_ui.s: src/view/piece/bonus_pill_ui.cpp.s
.PHONY : src/view/piece/bonus_pill_ui.s

# target to generate assembly for a file
src/view/piece/bonus_pill_ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/piece/bonus_pill_ui.cpp.s
.PHONY : src/view/piece/bonus_pill_ui.cpp.s

src/view/piece/brick_ui.obj: src/view/piece/brick_ui.cpp.obj
.PHONY : src/view/piece/brick_ui.obj

# target to build an object file
src/view/piece/brick_ui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/piece/brick_ui.cpp.obj
.PHONY : src/view/piece/brick_ui.cpp.obj

src/view/piece/brick_ui.i: src/view/piece/brick_ui.cpp.i
.PHONY : src/view/piece/brick_ui.i

# target to preprocess a source file
src/view/piece/brick_ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/piece/brick_ui.cpp.i
.PHONY : src/view/piece/brick_ui.cpp.i

src/view/piece/brick_ui.s: src/view/piece/brick_ui.cpp.s
.PHONY : src/view/piece/brick_ui.s

# target to generate assembly for a file
src/view/piece/brick_ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/piece/brick_ui.cpp.s
.PHONY : src/view/piece/brick_ui.cpp.s

src/view/piece/lazer_ui.obj: src/view/piece/lazer_ui.cpp.obj
.PHONY : src/view/piece/lazer_ui.obj

# target to build an object file
src/view/piece/lazer_ui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/piece/lazer_ui.cpp.obj
.PHONY : src/view/piece/lazer_ui.cpp.obj

src/view/piece/lazer_ui.i: src/view/piece/lazer_ui.cpp.i
.PHONY : src/view/piece/lazer_ui.i

# target to preprocess a source file
src/view/piece/lazer_ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/piece/lazer_ui.cpp.i
.PHONY : src/view/piece/lazer_ui.cpp.i

src/view/piece/lazer_ui.s: src/view/piece/lazer_ui.cpp.s
.PHONY : src/view/piece/lazer_ui.s

# target to generate assembly for a file
src/view/piece/lazer_ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/piece/lazer_ui.cpp.s
.PHONY : src/view/piece/lazer_ui.cpp.s

src/view/piece/racket_ui.obj: src/view/piece/racket_ui.cpp.obj
.PHONY : src/view/piece/racket_ui.obj

# target to build an object file
src/view/piece/racket_ui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/piece/racket_ui.cpp.obj
.PHONY : src/view/piece/racket_ui.cpp.obj

src/view/piece/racket_ui.i: src/view/piece/racket_ui.cpp.i
.PHONY : src/view/piece/racket_ui.i

# target to preprocess a source file
src/view/piece/racket_ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/piece/racket_ui.cpp.i
.PHONY : src/view/piece/racket_ui.cpp.i

src/view/piece/racket_ui.s: src/view/piece/racket_ui.cpp.s
.PHONY : src/view/piece/racket_ui.s

# target to generate assembly for a file
src/view/piece/racket_ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/piece/racket_ui.cpp.s
.PHONY : src/view/piece/racket_ui.cpp.s

src/view/piece/wall_ui.obj: src/view/piece/wall_ui.cpp.obj
.PHONY : src/view/piece/wall_ui.obj

# target to build an object file
src/view/piece/wall_ui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/piece/wall_ui.cpp.obj
.PHONY : src/view/piece/wall_ui.cpp.obj

src/view/piece/wall_ui.i: src/view/piece/wall_ui.cpp.i
.PHONY : src/view/piece/wall_ui.i

# target to preprocess a source file
src/view/piece/wall_ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/piece/wall_ui.cpp.i
.PHONY : src/view/piece/wall_ui.cpp.i

src/view/piece/wall_ui.s: src/view/piece/wall_ui.cpp.s
.PHONY : src/view/piece/wall_ui.s

# target to generate assembly for a file
src/view/piece/wall_ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\arkanoid.dir\build.make CMakeFiles/arkanoid.dir/src/view/piece/wall_ui.cpp.s
.PHONY : src/view/piece/wall_ui.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... arkanoid
	@echo ... src/controller/controller_game.obj
	@echo ... src/controller/controller_game.i
	@echo ... src/controller/controller_game.s
	@echo ... src/controller/level_manager/level_manager.obj
	@echo ... src/controller/level_manager/level_manager.i
	@echo ... src/controller/level_manager/level_manager.s
	@echo ... src/log/log.obj
	@echo ... src/log/log.i
	@echo ... src/log/log.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/model/ball/ball.obj
	@echo ... src/model/ball/ball.i
	@echo ... src/model/ball/ball.s
	@echo ... src/model/bonus/abstract_timed_bonus.obj
	@echo ... src/model/bonus/abstract_timed_bonus.i
	@echo ... src/model/bonus/abstract_timed_bonus.s
	@echo ... src/model/bonus/basic_timed_bonus.obj
	@echo ... src/model/bonus/basic_timed_bonus.i
	@echo ... src/model/bonus/basic_timed_bonus.s
	@echo ... src/model/bonus/slowdown_bonus.obj
	@echo ... src/model/bonus/slowdown_bonus.i
	@echo ... src/model/bonus/slowdown_bonus.s
	@echo ... src/model/bonus_pill/bonus_pill.obj
	@echo ... src/model/bonus_pill/bonus_pill.i
	@echo ... src/model/bonus_pill/bonus_pill.s
	@echo ... src/model/border/border.obj
	@echo ... src/model/border/border.i
	@echo ... src/model/border/border.s
	@echo ... src/model/bounceable/bounceable.obj
	@echo ... src/model/bounceable/bounceable.i
	@echo ... src/model/bounceable/bounceable.s
	@echo ... src/model/brick/abstract_brick.obj
	@echo ... src/model/brick/abstract_brick.i
	@echo ... src/model/brick/abstract_brick.s
	@echo ... src/model/brick/basic_brick.obj
	@echo ... src/model/brick/basic_brick.i
	@echo ... src/model/brick/basic_brick.s
	@echo ... src/model/brick/gold_brick.obj
	@echo ... src/model/brick/gold_brick.i
	@echo ... src/model/brick/gold_brick.s
	@echo ... src/model/game_board/game_board.obj
	@echo ... src/model/game_board/game_board.i
	@echo ... src/model/game_board/game_board.s
	@echo ... src/model/lazer/lazer.obj
	@echo ... src/model/lazer/lazer.i
	@echo ... src/model/lazer/lazer.s
	@echo ... src/model/life_counter/life_counter.obj
	@echo ... src/model/life_counter/life_counter.i
	@echo ... src/model/life_counter/life_counter.s
	@echo ... src/model/racket/racket.obj
	@echo ... src/model/racket/racket.i
	@echo ... src/model/racket/racket.s
	@echo ... src/model/rectangle_shape/rectangle_shape.obj
	@echo ... src/model/rectangle_shape/rectangle_shape.i
	@echo ... src/model/rectangle_shape/rectangle_shape.s
	@echo ... src/model/score_manager/score_manager.obj
	@echo ... src/model/score_manager/score_manager.i
	@echo ... src/model/score_manager/score_manager.s
	@echo ... src/model/vec2/vec2.obj
	@echo ... src/model/vec2/vec2.i
	@echo ... src/model/vec2/vec2.s
	@echo ... src/view/canvas/canvas.obj
	@echo ... src/view/canvas/canvas.i
	@echo ... src/view/canvas/canvas.s
	@echo ... src/view/color/colors.obj
	@echo ... src/view/color/colors.i
	@echo ... src/view/color/colors.s
	@echo ... src/view/display_game/display_game.obj
	@echo ... src/view/display_game/display_game.i
	@echo ... src/view/display_game/display_game.s
	@echo ... src/view/figures/forme.obj
	@echo ... src/view/figures/forme.i
	@echo ... src/view/figures/forme.s
	@echo ... src/view/figures/point.obj
	@echo ... src/view/figures/point.i
	@echo ... src/view/figures/point.s
	@echo ... src/view/piece/ball_ui.obj
	@echo ... src/view/piece/ball_ui.i
	@echo ... src/view/piece/ball_ui.s
	@echo ... src/view/piece/bonus_pill_ui.obj
	@echo ... src/view/piece/bonus_pill_ui.i
	@echo ... src/view/piece/bonus_pill_ui.s
	@echo ... src/view/piece/brick_ui.obj
	@echo ... src/view/piece/brick_ui.i
	@echo ... src/view/piece/brick_ui.s
	@echo ... src/view/piece/lazer_ui.obj
	@echo ... src/view/piece/lazer_ui.i
	@echo ... src/view/piece/lazer_ui.s
	@echo ... src/view/piece/racket_ui.obj
	@echo ... src/view/piece/racket_ui.i
	@echo ... src/view/piece/racket_ui.s
	@echo ... src/view/piece/wall_ui.obj
	@echo ... src/view/piece/wall_ui.i
	@echo ... src/view/piece/wall_ui.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

