name: C++ RaquetteBaballe Build (with Make + Cache)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache CMake Build
      uses: actions/cache@v4
      with:
        path: build/
        key: build-cache-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          build-cache-${{ runner.os }}-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install liballegro5-dev

    - name: Build with Make
      run: |
        make
